# Generated by Django 5.1.1 on 2024-09-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site_tour',
            fields=[
                ('id_site_tour', models.AutoField(primary_key=True, serialize=False)),
                ('site_name', models.CharField(blank=True, max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('url', models.URLField(verbose_name='Url')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Imagen')),
                ('adress', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dirección')),
                ('coordinates', models.CharField(blank=True, max_length=100, null=True, verbose_name='Coordenadas')),
                ('journey_time', models.TimeField(blank=True, null=True, verbose_name='Tiempo de recorrido')),
                ('site_type', models.IntegerField(blank=True, choices=[(1, 'Interior'), (2, 'Exterior')], default=1, null=True, verbose_name='Tipo')),
                ('accesibility', models.TextField(blank=True, null=True, verbose_name='Accesibilidad')),
            ],
        ),
    ]
