# Generated by Django 5.1.1 on 2024-09-16 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_tour', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site_tour',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
