# Generated by Django 5.1.1 on 2024-09-30 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_tour', '0002_site_tour_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site_tour',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagen'),
        ),
    ]
