# Generated by Django 5.1.1 on 2024-09-30 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_tour', '0003_alter_site_tour_image'),
        ('tag', '0002_rename_id_site_site_tag_site_tour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site_tour',
            name='tags',
            field=models.ManyToManyField(through='tag.Site_tag', to='tag.tag'),
        ),
    ]
