# Generated by Django 5.1.1 on 2024-09-08 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('site_tour', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id_tag', models.IntegerField(primary_key=True, serialize=False)),
                ('tag', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Etiqueta')),
            ],
        ),
        migrations.CreateModel(
            name='Site_tag',
            fields=[
                ('id_site_tag', models.IntegerField(primary_key=True, serialize=False)),
                ('id_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_tour.site_tour')),
                ('id_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tag.tag')),
            ],
        ),
    ]
