# Generated by Django 5.1.1 on 2024-09-30 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_tour', '0003_alter_site_tour_image'),
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site_tag',
            old_name='id_site',
            new_name='site_tour',
        ),
        migrations.RenameField(
            model_name='site_tag',
            old_name='id_tag',
            new_name='tag',
        ),
        migrations.AlterUniqueTogether(
            name='site_tag',
            unique_together={('site_tour', 'tag')},
        ),
    ]
