# Generated by Django 5.1.1 on 2024-10-12 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0002_alter_site_tag_id_site_tag_alter_tag_id_tag_and_more'),
        ('tag', '0002_rename_id_site_site_tag_site_tour_and_more'),
    ]

    operations = [
    ]
