# Generated by Django 5.1.1 on 2024-10-12 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0003_merge_20241012_1716'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='site_tag',
            unique_together=set(),
        ),
    ]
